name: todark
description: Task management app.

publish_to: "none"

version: 1.4.0+30

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.18.1
  isar: ^3.1.0+1
  iconsax: ^0.0.8
  timezone: ^0.9.2
  file_picker: ^5.5.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.14
  bottom_picker: ^2.0.4
  dynamic_color: ^1.6.6
  path_provider: ^2.1.1
  table_calendar: ^3.0.9
  flutter_timezone: ^1.0.7
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  flex_color_picker: ^3.3.0
  isar_flutter_libs: ^3.1.0+1
  permission_handler: ^10.4.5
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  isar_generator: ^3.1.0+1
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
