name: todark
description: Task management application.

publish_to: "none"

version: 1.5.4+44

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  gap: ^3.0.1
  path: ^1.9.0
  intl: ^0.19.0
  timezone: ^0.9.4
  # workmanager: ^0.5.2
  # home_widget: ^0.7.0
  # quick_actions: ^1.0.8
  restart_app: ^1.3.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  iconsax_plus: ^1.0.0
  time_machine: ^0.9.17
  dynamic_color: ^1.7.0
  path_provider: ^2.1.5
  file_selector: ^1.0.3
  table_calendar: ^3.1.2
  flutter_timezone: ^3.0.1
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  flex_color_picker: ^3.6.0
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  omni_datetime_picker: ^2.0.5
  line_awesome_flutter: ^3.0.1
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^18.0.0
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
