name: todark
description: Task management application

publish_to: "none"

version: 1.5.2+42

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  gap: ^3.0.1
  path: ^1.9.0
  intl: ^0.19.0
  isar:
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  iconsax: ^0.0.8
  timezone: ^0.9.4
  # workmanager: ^0.5.2
  # home_widget: ^0.6.0
  restart_app: ^1.2.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  time_machine: ^0.9.17
  bottom_picker: ^2.8.0
  dynamic_color: ^1.7.0
  path_provider: ^2.1.4
  file_selector: ^1.0.3
  table_calendar: ^3.1.2
  flutter_timezone: ^2.1.0
  device_info_plus: ^10.1.1
  package_info_plus: ^8.0.1
  flex_color_picker: ^3.5.1
  isar_flutter_libs:
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^17.2.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  isar_generator: 
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/google_fonts/
