name: todark
description: A new Flutter project.

publish_to: "none"

version: 1.3.6+26

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  isar: ^3.0.5
  intl: ^0.17.0
  swipe: ^0.0.1
  iconsax: ^0.0.8
  file_picker: ^5.2.7
  url_launcher: ^6.1.10
  path_provider: ^2.0.14
  table_calendar: ^3.0.8
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  isar_flutter_libs: ^3.0.5
  flex_color_picker: ^3.2.0
  flutter_easyloading: ^3.0.5
  permission_handler: ^10.2.0
  custom_navigation_bar: ^0.8.2
  sleek_circular_slider: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#1F1F1F"
  adaptive_icon_foreground: "assets/icons/icon_adaptive.png"

flutter_native_splash:
  color: "#121212"
  image: "assets/icons/icon_splash.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
